# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fv/Dev/openFrameworks/ofx-projects/openFrameworks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fv/Dev/openFrameworks/ofx-projects/openFrameworks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fv/Dev/openFrameworks/ofx-projects/openFrameworks/CMakeFiles /home/fv/Dev/openFrameworks/ofx-projects/openFrameworks/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fv/Dev/openFrameworks/ofx-projects/openFrameworks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openFrameworksShared

# Build rule for target.
openFrameworksShared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openFrameworksShared
.PHONY : openFrameworksShared

# fast build rule for target.
openFrameworksShared/fast:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/build
.PHONY : openFrameworksShared/fast

#=============================================================================
# Target rules for targets named openFrameworksStatic

# Build rule for target.
openFrameworksStatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openFrameworksStatic
.PHONY : openFrameworksStatic

# fast build rule for target.
openFrameworksStatic/fast:
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/build
.PHONY : openFrameworksStatic/fast

app/ofAppGlutWindow.o: app/ofAppGlutWindow.cpp.o
.PHONY : app/ofAppGlutWindow.o

# target to build an object file
app/ofAppGlutWindow.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/app/ofAppGlutWindow.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/app/ofAppGlutWindow.cpp.o
.PHONY : app/ofAppGlutWindow.cpp.o

app/ofAppGlutWindow.i: app/ofAppGlutWindow.cpp.i
.PHONY : app/ofAppGlutWindow.i

# target to preprocess a source file
app/ofAppGlutWindow.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/app/ofAppGlutWindow.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/app/ofAppGlutWindow.cpp.i
.PHONY : app/ofAppGlutWindow.cpp.i

app/ofAppGlutWindow.s: app/ofAppGlutWindow.cpp.s
.PHONY : app/ofAppGlutWindow.s

# target to generate assembly for a file
app/ofAppGlutWindow.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/app/ofAppGlutWindow.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/app/ofAppGlutWindow.cpp.s
.PHONY : app/ofAppGlutWindow.cpp.s

app/ofAppRunner.o: app/ofAppRunner.cpp.o
.PHONY : app/ofAppRunner.o

# target to build an object file
app/ofAppRunner.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/app/ofAppRunner.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/app/ofAppRunner.cpp.o
.PHONY : app/ofAppRunner.cpp.o

app/ofAppRunner.i: app/ofAppRunner.cpp.i
.PHONY : app/ofAppRunner.i

# target to preprocess a source file
app/ofAppRunner.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/app/ofAppRunner.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/app/ofAppRunner.cpp.i
.PHONY : app/ofAppRunner.cpp.i

app/ofAppRunner.s: app/ofAppRunner.cpp.s
.PHONY : app/ofAppRunner.s

# target to generate assembly for a file
app/ofAppRunner.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/app/ofAppRunner.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/app/ofAppRunner.cpp.s
.PHONY : app/ofAppRunner.cpp.s

communication/ofArduino.o: communication/ofArduino.cpp.o
.PHONY : communication/ofArduino.o

# target to build an object file
communication/ofArduino.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofArduino.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofArduino.cpp.o
.PHONY : communication/ofArduino.cpp.o

communication/ofArduino.i: communication/ofArduino.cpp.i
.PHONY : communication/ofArduino.i

# target to preprocess a source file
communication/ofArduino.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofArduino.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofArduino.cpp.i
.PHONY : communication/ofArduino.cpp.i

communication/ofArduino.s: communication/ofArduino.cpp.s
.PHONY : communication/ofArduino.s

# target to generate assembly for a file
communication/ofArduino.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofArduino.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofArduino.cpp.s
.PHONY : communication/ofArduino.cpp.s

communication/ofSerial.o: communication/ofSerial.cpp.o
.PHONY : communication/ofSerial.o

# target to build an object file
communication/ofSerial.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofSerial.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofSerial.cpp.o
.PHONY : communication/ofSerial.cpp.o

communication/ofSerial.i: communication/ofSerial.cpp.i
.PHONY : communication/ofSerial.i

# target to preprocess a source file
communication/ofSerial.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofSerial.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofSerial.cpp.i
.PHONY : communication/ofSerial.cpp.i

communication/ofSerial.s: communication/ofSerial.cpp.s
.PHONY : communication/ofSerial.s

# target to generate assembly for a file
communication/ofSerial.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofSerial.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofSerial.cpp.s
.PHONY : communication/ofSerial.cpp.s

communication/ofStandardFirmata.o: communication/ofStandardFirmata.cpp.o
.PHONY : communication/ofStandardFirmata.o

# target to build an object file
communication/ofStandardFirmata.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofStandardFirmata.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofStandardFirmata.cpp.o
.PHONY : communication/ofStandardFirmata.cpp.o

communication/ofStandardFirmata.i: communication/ofStandardFirmata.cpp.i
.PHONY : communication/ofStandardFirmata.i

# target to preprocess a source file
communication/ofStandardFirmata.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofStandardFirmata.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofStandardFirmata.cpp.i
.PHONY : communication/ofStandardFirmata.cpp.i

communication/ofStandardFirmata.s: communication/ofStandardFirmata.cpp.s
.PHONY : communication/ofStandardFirmata.s

# target to generate assembly for a file
communication/ofStandardFirmata.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/communication/ofStandardFirmata.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/communication/ofStandardFirmata.cpp.s
.PHONY : communication/ofStandardFirmata.cpp.s

graphics/ofBitmapFont.o: graphics/ofBitmapFont.cpp.o
.PHONY : graphics/ofBitmapFont.o

# target to build an object file
graphics/ofBitmapFont.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofBitmapFont.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofBitmapFont.cpp.o
.PHONY : graphics/ofBitmapFont.cpp.o

graphics/ofBitmapFont.i: graphics/ofBitmapFont.cpp.i
.PHONY : graphics/ofBitmapFont.i

# target to preprocess a source file
graphics/ofBitmapFont.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofBitmapFont.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofBitmapFont.cpp.i
.PHONY : graphics/ofBitmapFont.cpp.i

graphics/ofBitmapFont.s: graphics/ofBitmapFont.cpp.s
.PHONY : graphics/ofBitmapFont.s

# target to generate assembly for a file
graphics/ofBitmapFont.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofBitmapFont.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofBitmapFont.cpp.s
.PHONY : graphics/ofBitmapFont.cpp.s

graphics/ofGraphics.o: graphics/ofGraphics.cpp.o
.PHONY : graphics/ofGraphics.o

# target to build an object file
graphics/ofGraphics.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofGraphics.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofGraphics.cpp.o
.PHONY : graphics/ofGraphics.cpp.o

graphics/ofGraphics.i: graphics/ofGraphics.cpp.i
.PHONY : graphics/ofGraphics.i

# target to preprocess a source file
graphics/ofGraphics.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofGraphics.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofGraphics.cpp.i
.PHONY : graphics/ofGraphics.cpp.i

graphics/ofGraphics.s: graphics/ofGraphics.cpp.s
.PHONY : graphics/ofGraphics.s

# target to generate assembly for a file
graphics/ofGraphics.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofGraphics.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofGraphics.cpp.s
.PHONY : graphics/ofGraphics.cpp.s

graphics/ofImage.o: graphics/ofImage.cpp.o
.PHONY : graphics/ofImage.o

# target to build an object file
graphics/ofImage.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofImage.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofImage.cpp.o
.PHONY : graphics/ofImage.cpp.o

graphics/ofImage.i: graphics/ofImage.cpp.i
.PHONY : graphics/ofImage.i

# target to preprocess a source file
graphics/ofImage.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofImage.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofImage.cpp.i
.PHONY : graphics/ofImage.cpp.i

graphics/ofImage.s: graphics/ofImage.cpp.s
.PHONY : graphics/ofImage.s

# target to generate assembly for a file
graphics/ofImage.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofImage.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofImage.cpp.s
.PHONY : graphics/ofImage.cpp.s

graphics/ofTexture.o: graphics/ofTexture.cpp.o
.PHONY : graphics/ofTexture.o

# target to build an object file
graphics/ofTexture.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofTexture.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofTexture.cpp.o
.PHONY : graphics/ofTexture.cpp.o

graphics/ofTexture.i: graphics/ofTexture.cpp.i
.PHONY : graphics/ofTexture.i

# target to preprocess a source file
graphics/ofTexture.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofTexture.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofTexture.cpp.i
.PHONY : graphics/ofTexture.cpp.i

graphics/ofTexture.s: graphics/ofTexture.cpp.s
.PHONY : graphics/ofTexture.s

# target to generate assembly for a file
graphics/ofTexture.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofTexture.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofTexture.cpp.s
.PHONY : graphics/ofTexture.cpp.s

graphics/ofTrueTypeFont.o: graphics/ofTrueTypeFont.cpp.o
.PHONY : graphics/ofTrueTypeFont.o

# target to build an object file
graphics/ofTrueTypeFont.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofTrueTypeFont.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofTrueTypeFont.cpp.o
.PHONY : graphics/ofTrueTypeFont.cpp.o

graphics/ofTrueTypeFont.i: graphics/ofTrueTypeFont.cpp.i
.PHONY : graphics/ofTrueTypeFont.i

# target to preprocess a source file
graphics/ofTrueTypeFont.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofTrueTypeFont.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofTrueTypeFont.cpp.i
.PHONY : graphics/ofTrueTypeFont.cpp.i

graphics/ofTrueTypeFont.s: graphics/ofTrueTypeFont.cpp.s
.PHONY : graphics/ofTrueTypeFont.s

# target to generate assembly for a file
graphics/ofTrueTypeFont.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/graphics/ofTrueTypeFont.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/graphics/ofTrueTypeFont.cpp.s
.PHONY : graphics/ofTrueTypeFont.cpp.s

sound/ofSoundPlayer.o: sound/ofSoundPlayer.cpp.o
.PHONY : sound/ofSoundPlayer.o

# target to build an object file
sound/ofSoundPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/sound/ofSoundPlayer.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/sound/ofSoundPlayer.cpp.o
.PHONY : sound/ofSoundPlayer.cpp.o

sound/ofSoundPlayer.i: sound/ofSoundPlayer.cpp.i
.PHONY : sound/ofSoundPlayer.i

# target to preprocess a source file
sound/ofSoundPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/sound/ofSoundPlayer.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/sound/ofSoundPlayer.cpp.i
.PHONY : sound/ofSoundPlayer.cpp.i

sound/ofSoundPlayer.s: sound/ofSoundPlayer.cpp.s
.PHONY : sound/ofSoundPlayer.s

# target to generate assembly for a file
sound/ofSoundPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/sound/ofSoundPlayer.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/sound/ofSoundPlayer.cpp.s
.PHONY : sound/ofSoundPlayer.cpp.s

sound/ofSoundStream.o: sound/ofSoundStream.cpp.o
.PHONY : sound/ofSoundStream.o

# target to build an object file
sound/ofSoundStream.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/sound/ofSoundStream.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/sound/ofSoundStream.cpp.o
.PHONY : sound/ofSoundStream.cpp.o

sound/ofSoundStream.i: sound/ofSoundStream.cpp.i
.PHONY : sound/ofSoundStream.i

# target to preprocess a source file
sound/ofSoundStream.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/sound/ofSoundStream.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/sound/ofSoundStream.cpp.i
.PHONY : sound/ofSoundStream.cpp.i

sound/ofSoundStream.s: sound/ofSoundStream.cpp.s
.PHONY : sound/ofSoundStream.s

# target to generate assembly for a file
sound/ofSoundStream.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/sound/ofSoundStream.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/sound/ofSoundStream.cpp.s
.PHONY : sound/ofSoundStream.cpp.s

utils/ofMath.o: utils/ofMath.cpp.o
.PHONY : utils/ofMath.o

# target to build an object file
utils/ofMath.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/utils/ofMath.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/utils/ofMath.cpp.o
.PHONY : utils/ofMath.cpp.o

utils/ofMath.i: utils/ofMath.cpp.i
.PHONY : utils/ofMath.i

# target to preprocess a source file
utils/ofMath.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/utils/ofMath.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/utils/ofMath.cpp.i
.PHONY : utils/ofMath.cpp.i

utils/ofMath.s: utils/ofMath.cpp.s
.PHONY : utils/ofMath.s

# target to generate assembly for a file
utils/ofMath.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/utils/ofMath.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/utils/ofMath.cpp.s
.PHONY : utils/ofMath.cpp.s

utils/ofUtils.o: utils/ofUtils.cpp.o
.PHONY : utils/ofUtils.o

# target to build an object file
utils/ofUtils.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/utils/ofUtils.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/utils/ofUtils.cpp.o
.PHONY : utils/ofUtils.cpp.o

utils/ofUtils.i: utils/ofUtils.cpp.i
.PHONY : utils/ofUtils.i

# target to preprocess a source file
utils/ofUtils.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/utils/ofUtils.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/utils/ofUtils.cpp.i
.PHONY : utils/ofUtils.cpp.i

utils/ofUtils.s: utils/ofUtils.cpp.s
.PHONY : utils/ofUtils.s

# target to generate assembly for a file
utils/ofUtils.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/utils/ofUtils.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/utils/ofUtils.cpp.s
.PHONY : utils/ofUtils.cpp.s

video/ofQtUtils.o: video/ofQtUtils.cpp.o
.PHONY : video/ofQtUtils.o

# target to build an object file
video/ofQtUtils.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofQtUtils.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofQtUtils.cpp.o
.PHONY : video/ofQtUtils.cpp.o

video/ofQtUtils.i: video/ofQtUtils.cpp.i
.PHONY : video/ofQtUtils.i

# target to preprocess a source file
video/ofQtUtils.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofQtUtils.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofQtUtils.cpp.i
.PHONY : video/ofQtUtils.cpp.i

video/ofQtUtils.s: video/ofQtUtils.cpp.s
.PHONY : video/ofQtUtils.s

# target to generate assembly for a file
video/ofQtUtils.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofQtUtils.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofQtUtils.cpp.s
.PHONY : video/ofQtUtils.cpp.s

video/ofUCUtils.o: video/ofUCUtils.cpp.o
.PHONY : video/ofUCUtils.o

# target to build an object file
video/ofUCUtils.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofUCUtils.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofUCUtils.cpp.o
.PHONY : video/ofUCUtils.cpp.o

video/ofUCUtils.i: video/ofUCUtils.cpp.i
.PHONY : video/ofUCUtils.i

# target to preprocess a source file
video/ofUCUtils.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofUCUtils.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofUCUtils.cpp.i
.PHONY : video/ofUCUtils.cpp.i

video/ofUCUtils.s: video/ofUCUtils.cpp.s
.PHONY : video/ofUCUtils.s

# target to generate assembly for a file
video/ofUCUtils.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofUCUtils.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofUCUtils.cpp.s
.PHONY : video/ofUCUtils.cpp.s

video/ofVideoGrabber.o: video/ofVideoGrabber.cpp.o
.PHONY : video/ofVideoGrabber.o

# target to build an object file
video/ofVideoGrabber.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofVideoGrabber.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofVideoGrabber.cpp.o
.PHONY : video/ofVideoGrabber.cpp.o

video/ofVideoGrabber.i: video/ofVideoGrabber.cpp.i
.PHONY : video/ofVideoGrabber.i

# target to preprocess a source file
video/ofVideoGrabber.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofVideoGrabber.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofVideoGrabber.cpp.i
.PHONY : video/ofVideoGrabber.cpp.i

video/ofVideoGrabber.s: video/ofVideoGrabber.cpp.s
.PHONY : video/ofVideoGrabber.s

# target to generate assembly for a file
video/ofVideoGrabber.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofVideoGrabber.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofVideoGrabber.cpp.s
.PHONY : video/ofVideoGrabber.cpp.s

video/ofVideoPlayer.o: video/ofVideoPlayer.cpp.o
.PHONY : video/ofVideoPlayer.o

# target to build an object file
video/ofVideoPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofVideoPlayer.cpp.o
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofVideoPlayer.cpp.o
.PHONY : video/ofVideoPlayer.cpp.o

video/ofVideoPlayer.i: video/ofVideoPlayer.cpp.i
.PHONY : video/ofVideoPlayer.i

# target to preprocess a source file
video/ofVideoPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofVideoPlayer.cpp.i
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofVideoPlayer.cpp.i
.PHONY : video/ofVideoPlayer.cpp.i

video/ofVideoPlayer.s: video/ofVideoPlayer.cpp.s
.PHONY : video/ofVideoPlayer.s

# target to generate assembly for a file
video/ofVideoPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/openFrameworksShared.dir/build.make CMakeFiles/openFrameworksShared.dir/video/ofVideoPlayer.cpp.s
	$(MAKE) -f CMakeFiles/openFrameworksStatic.dir/build.make CMakeFiles/openFrameworksStatic.dir/video/ofVideoPlayer.cpp.s
.PHONY : video/ofVideoPlayer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... openFrameworksShared"
	@echo "... openFrameworksStatic"
	@echo "... rebuild_cache"
	@echo "... app/ofAppGlutWindow.o"
	@echo "... app/ofAppGlutWindow.i"
	@echo "... app/ofAppGlutWindow.s"
	@echo "... app/ofAppRunner.o"
	@echo "... app/ofAppRunner.i"
	@echo "... app/ofAppRunner.s"
	@echo "... communication/ofArduino.o"
	@echo "... communication/ofArduino.i"
	@echo "... communication/ofArduino.s"
	@echo "... communication/ofSerial.o"
	@echo "... communication/ofSerial.i"
	@echo "... communication/ofSerial.s"
	@echo "... communication/ofStandardFirmata.o"
	@echo "... communication/ofStandardFirmata.i"
	@echo "... communication/ofStandardFirmata.s"
	@echo "... graphics/ofBitmapFont.o"
	@echo "... graphics/ofBitmapFont.i"
	@echo "... graphics/ofBitmapFont.s"
	@echo "... graphics/ofGraphics.o"
	@echo "... graphics/ofGraphics.i"
	@echo "... graphics/ofGraphics.s"
	@echo "... graphics/ofImage.o"
	@echo "... graphics/ofImage.i"
	@echo "... graphics/ofImage.s"
	@echo "... graphics/ofTexture.o"
	@echo "... graphics/ofTexture.i"
	@echo "... graphics/ofTexture.s"
	@echo "... graphics/ofTrueTypeFont.o"
	@echo "... graphics/ofTrueTypeFont.i"
	@echo "... graphics/ofTrueTypeFont.s"
	@echo "... sound/ofSoundPlayer.o"
	@echo "... sound/ofSoundPlayer.i"
	@echo "... sound/ofSoundPlayer.s"
	@echo "... sound/ofSoundStream.o"
	@echo "... sound/ofSoundStream.i"
	@echo "... sound/ofSoundStream.s"
	@echo "... utils/ofMath.o"
	@echo "... utils/ofMath.i"
	@echo "... utils/ofMath.s"
	@echo "... utils/ofUtils.o"
	@echo "... utils/ofUtils.i"
	@echo "... utils/ofUtils.s"
	@echo "... video/ofQtUtils.o"
	@echo "... video/ofQtUtils.i"
	@echo "... video/ofQtUtils.s"
	@echo "... video/ofUCUtils.o"
	@echo "... video/ofUCUtils.i"
	@echo "... video/ofUCUtils.s"
	@echo "... video/ofVideoGrabber.o"
	@echo "... video/ofVideoGrabber.i"
	@echo "... video/ofVideoGrabber.s"
	@echo "... video/ofVideoPlayer.o"
	@echo "... video/ofVideoPlayer.i"
	@echo "... video/ofVideoPlayer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

